=== smoilla/PrescriptionManagement/PMJaxB/src/main/resources/schema/FindPrescriptionsResponse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/FindPrescriptionsResponse"
	xmlns:tns="http://www.example.org/FindPrescriptionsResponse"
	elementFormDefault="qualified">
	<xsd:element name="FindPrescriptionsResponse">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="prescriptions" type="tns:ArrayOfPrescriptions" />
				<xsd:element name="numberOfPrescriptions" type="xsd:string" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="ArrayOfPrescriptions">
		<xsd:sequence>
			<xsd:element name="prescription" type="tns:Prescription"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>



	<xsd:complexType name="Prescription">
		<xsd:sequence>
			<xsd:element name="rxNumber" type="xsd:string" />
			<xsd:element name="locaNumber" type="xsd:string" />
			<xsd:element name="dateOfService" type="xsd:string" />
			<xsd:element name="daysSupplyQuantity" type="xsd:string" />
			<xsd:element name="lastFilllDate" type="xsd:string" />
			<xsd:element name="dosageQuantity" type="xsd:string" />
			<xsd:element name="fillingPharmacy" type="xsd:string" />
			<xsd:element name="enrollmentIndicator" type="xsd:string" />
			<xsd:element name="isEligible" type="xsd:string" />
			<xsd:element name="nonEligibleReasonCode" type="xsd:string" />
			<xsd:element name="prescriber" type="tns:Prescriber" />
			<xsd:element name="drug" type="tns:Drug" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Address">
		<xsd:sequence>
			<xsd:element name="line1" type="xsd:string" />
			<xsd:element name="line2" type="xsd:string" />
			<xsd:element name="state" type="xsd:string" />
			<xsd:element name="city" type="xsd:string" />
			<xsd:element name="zipcode" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="Prescriber">
		<xsd:sequence>
			<xsd:element name="id" type="xsd:string" />
			<xsd:element name="firstName" type="xsd:string" />
			<xsd:element name="lastName" type="xsd:string" />
			<xsd:element name="homeAddress" type="tns:Address" />
			<xsd:element name="workAddress" type="tns:Address" />
			<xsd:element name="licenseNumber" type="xsd:string" />

		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Drug">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" />
			<xsd:element name="type" type="xsd:string" />
			<xsd:element name="speciality" type="xsd:string" />
			<xsd:element name="ndc" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>


</xsd:schema>

=== smoilla/PrescriptionManagement/PMJaxB/src/main/resources/schema/FindPrescriptionsResponse.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:FindPrescriptionsResponse xmlns:tns="http://www.example.org/FindPrescriptionsResponse" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/FindPrescriptionsResponse FindPrescriptionsResponse.xsd ">
  <tns:prescriptions>
    <tns:prescription>
      <tns:rxNumber>tns:rxNumber</tns:rxNumber>
      <tns:locaNumber>tns:locaNumber</tns:locaNumber>
      <tns:dateOfService>tns:dateOfService</tns:dateOfService>
      <tns:daysSupplyQuantity>tns:daysSupplyQuantity</tns:daysSupplyQuantity>
      <tns:lastFilllDate>tns:lastFilllDate</tns:lastFilllDate>
      <tns:dosageQuantity>tns:dosageQuantity</tns:dosageQuantity>
      <tns:fillingPharmacy>tns:fillingPharmacy</tns:fillingPharmacy>
      <tns:enrollmentIndicator>tns:enrollmentIndicator</tns:enrollmentIndicator>
      <tns:isEligible>tns:isEligible</tns:isEligible>
      <tns:nonEligibleReasonCode>tns:nonEligibleReasonCode</tns:nonEligibleReasonCode>
      <tns:prescriber>
        <tns:id>tns:id</tns:id>
        <tns:firstName>tns:firstName</tns:firstName>
        <tns:lastName>tns:lastName</tns:lastName>
        <tns:homeAddress>
          <tns:line1>tns:line1</tns:line1>
          <tns:line2>tns:line2</tns:line2>
          <tns:state>tns:state</tns:state>
          <tns:city>tns:city</tns:city>
          <tns:zipcode>tns:zipcode</tns:zipcode>
        </tns:homeAddress>
        <tns:workAddress>
          <tns:line1>tns:line1</tns:line1>
          <tns:line2>tns:line2</tns:line2>
          <tns:state>tns:state</tns:state>
          <tns:city>tns:city</tns:city>
          <tns:zipcode>tns:zipcode</tns:zipcode>
        </tns:workAddress>
        <tns:licenseNumber>tns:licenseNumber</tns:licenseNumber>
      </tns:prescriber>
      <tns:drug>
        <tns:name>tns:name</tns:name>
        <tns:type>tns:type</tns:type>
        <tns:speciality>tns:speciality</tns:speciality>
        <tns:ndc>tns:ndc</tns:ndc>
      </tns:drug>
    </tns:prescription>
  </tns:prescriptions>
  <tns:numberOfPrescriptions>tns:numberOfPrescriptions</tns:numberOfPrescriptions>
</tns:FindPrescriptionsResponse>
